language: php

php:
  - 5.6
  - 7.0

before_script:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v
